# -*- coding: utf-8 -*-
"""
70_evolutionary_indifference.py

Build S7_Evolutionary_Stats:
- Total_Mutations per sample
- CDS_Fraction per sample = (#Category == 'CDS') / total

IMPORTANT:
- Uses outputs_functional_shielding/tables/events_annotated_v2.csv.gz
  (must exist; generated by step 50)

Output:
  outputs_functional_shielding/tables/evolutionary_stats.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from pipeline_utils import resolve_project_paths


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-root", default=None)
    args = ap.parse_args()

    paths = resolve_project_paths(args.project_root)

    ann_path = paths.outputs_functional / "tables" / "events_annotated_v2.csv.gz"
    if not ann_path.exists():
        raise FileNotFoundError(f"events_annotated_v2 not found: {ann_path}. Run step 50 first.")

    print(f"[INFO] Loading annotated events: {ann_path}")
    df = pd.read_csv(ann_path, compression="gzip", low_memory=False)

    required = {"sample_id", "rad_type", "dose_Gy", "Category"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns in annotated events: {sorted(missing)}")

    # Normalize dtypes
    df["sample_id"] = pd.to_numeric(df["sample_id"], errors="coerce").astype("Int64")
    df = df.dropna(subset=["sample_id"]).copy()
    df["sample_id"] = df["sample_id"].astype(int)

    df["rad_type"] = df["rad_type"].astype(str).str.lower().str.strip()
    df["dose_Gy"] = pd.to_numeric(df["dose_Gy"], errors="coerce").astype("Int64")
    df = df.dropna(subset=["dose_Gy"]).copy()
    df["dose_Gy"] = df["dose_Gy"].astype(int)

    df["Category"] = df["Category"].astype(str).str.strip()

    # Total mutations per sample
    total = df.groupby(["sample_id", "rad_type", "dose_Gy"]).size().rename("Total_Mutations").reset_index()

    # CDS mutations per sample
    cds = (
        df[df["Category"] == "CDS"]
        .groupby(["sample_id", "rad_type", "dose_Gy"])
        .size()
        .rename("CDS_Mutations")
        .reset_index()
    )

    out = total.merge(cds, on=["sample_id", "rad_type", "dose_Gy"], how="left")
    out["CDS_Mutations"] = out["CDS_Mutations"].fillna(0).astype(int)
    out["CDS_Fraction"] = out["CDS_Mutations"] / out["Total_Mutations"]

    # Final columns for S7 (paper-like)
    out = out[["sample_id", "rad_type", "dose_Gy", "Total_Mutations", "CDS_Fraction"]].copy()
    out = out.sort_values(["rad_type", "dose_Gy", "sample_id"]).reset_index(drop=True)

    out_path = paths.outputs_functional / "tables" / "evolutionary_stats.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(out_path, index=False, float_format="%.6f")

    print(f"[OK] Saved: {out_path} ({len(out)} samples)")
    # quick sanity
    print("[INFO] CDS_Fraction summary (min/mean/max):",
          float(out["CDS_Fraction"].min()),
          float(out["CDS_Fraction"].mean()),
          float(out["CDS_Fraction"].max()))


if __name__ == "__main__":
    main()
